enum BlockStatus {
	PLANTED = 'PLANTED',
	NOT_PLANTED = 'NOT PLANTED',
	WASTED = 'WASTED',
	FERTILIZED = 'FERTILIZED',
	GROWN = 'GROWN',
	GROWN_AFTER_FERTILIZATION = 'GROWN AFTER FERTILIZATION',
	DEAD = 'DEAD',
}

export default BlockStatus;

